"""TAC-FUSE local-first command and control demo package."""

from tac_fuse.connectivity import (
    ConnectivityController,
    ConnectivityMode,
    create_connectivity_controller,
)
from tac_fuse.foundry import (
    SyncBoundaryViolation,
    assert_sync_allowed,
    can_upload,
    has_upload_credentials,
)
from tac_fuse.foundry_export import (
    build_foundry_export,
    write_foundry_artifacts,
    write_foundry_export,
)
from tac_fuse.local_c2 import (
    C2_COMMAND_OPS,
    C2Command,
    C2CommandReceipt,
    C2CommandStatus,
    LocalC2Authority,
    SyncGate,
    SyncGateStatus,
    TrackAuthority,
    TrackStalenessPolicy,
    UnknownCommandError,
    flush_sync_queue,
    issue_c2_command,
    prepare_sync_payload,
)
from tac_fuse.mission_state import MissionStateStore
from tac_fuse.npu_siglip import (
    FIELD_CONDITION_LABELS,
    MODEL_ID,
    FieldConditionResult,
    FieldConditionScore,
    IntelNPUSigLIP2Adapter,
    NPUStatus,
)
from tac_fuse.pov import (
    DronePOVFrame,
    POVObject,
    generate_pov_sequence,
    project_tracks_to_pov,
    render_svg_pov,
)
from tac_fuse.power_posture import (
    DENIED_CONNECTIVITY_RATIONALE,
    LATENCY_BUDGET_MS,
    WORKLOAD_REGISTRY,
    BatteryAssumption,
    ComputeTier,
    DeniedConnectivityGuide,
    LatencyBudget,
    PowerPosture,
    PowerPostureConfig,
    PowerPostureManager,
    PowerSource,
    WorkloadClass,
)
from tac_fuse.ray_query import (
    BVHPrimitive,
    RayQueryResult,
    RayQueryStatus,
    default_primitives,
    evaluate_bvh,
    inspect_ray_runtime,
)
from tac_fuse.replay import (
    AssetTrack,
    RestrictedEntry,
    RouteConflict,
    SeededReplayEngine,
    demo_conflicts,
    demo_restricted_entries,
    generate_scenario,
)
from tac_fuse.rt_control import (
    RTControlDecision,
    RTControlPlan,
    RTControlUnavailable,
    backend_label,
    issue_rt_control_plan,
    plan_rt_control,
)

__all__ = [
    "AssetTrack",
    "BVHPrimitive",
    "BatteryAssumption",
    "C2_COMMAND_OPS",
    "C2Command",
    "C2CommandReceipt",
    "C2CommandStatus",
    "ComputeTier",
    "ConnectivityController",
    "ConnectivityMode",
    "DeniedConnectivityGuide",
    "DronePOVFrame",
    "DENIED_CONNECTIVITY_RATIONALE",
    "FIELD_CONDITION_LABELS",
    "FieldConditionResult",
    "FieldConditionScore",
    "IntelNPUSigLIP2Adapter",
    "LATENCY_BUDGET_MS",
    "LocalC2Authority",
    "LatencyBudget",
    "MODEL_ID",
    "MissionStateStore",
    "NPUStatus",
    "POVObject",
    "PowerPosture",
    "PowerPostureConfig",
    "PowerPostureManager",
    "PowerSource",
    "RayQueryResult",
    "RayQueryStatus",
    "RestrictedEntry",
    "RouteConflict",
    "RTControlDecision",
    "RTControlPlan",
    "RTControlUnavailable",
    "SeededReplayEngine",
    "SyncBoundaryViolation",
    "SyncGate",
    "SyncGateStatus",
    "TrackAuthority",
    "TrackStalenessPolicy",
    "UnknownCommandError",
    "WORKLOAD_REGISTRY",
    "WorkloadClass",
    "assert_sync_allowed",
    "backend_label",
    "build_foundry_export",
    "can_upload",
    "create_connectivity_controller",
    "demo_conflicts",
    "demo_restricted_entries",
    "default_primitives",
    "evaluate_bvh",
    "flush_sync_queue",
    "generate_pov_sequence",
    "generate_scenario",
    "has_upload_credentials",
    "inspect_ray_runtime",
    "issue_rt_control_plan",
    "issue_c2_command",
    "plan_rt_control",
    "prepare_sync_payload",
    "project_tracks_to_pov",
    "render_svg_pov",
    "write_foundry_artifacts",
    "write_foundry_export",
]
