"""Write the Strix compute readiness artifact consumed by the static demo.

The browser demo is often opened directly from ``web/index.html`` without a
local HTTP server.  A small JavaScript artifact is more reliable than JSON in
that mode because the browser can load it via a normal script tag under
``file://``.
"""

from __future__ import annotations

import argparse
import json
import socket
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from tac_fuse.npu_siglip import IntelNPUSigLIP2Adapter
from tac_fuse.ray_query import inspect_ray_runtime

DEFAULT_OUTPUT = Path("web/strix_compute_status.js")
DEFAULT_MODEL_DIR = Path("models/siglip2-field-npu")
GLOBAL_NAME = "TAC_FUSE_STRIX_COMPUTE"


def _to_dict(status: Any) -> dict[str, Any]:
    if hasattr(status, "to_dict"):
        return dict(status.to_dict())
    if isinstance(status, dict):
        return dict(status)
    raise TypeError(f"unsupported status object: {type(status)!r}")


def _compute_mode(ray: dict[str, Any], npu: dict[str, Any]) -> str:
    if ray.get("accelerated") and npu.get("ready"):
        return "strix_cuda_npu"
    if ray.get("accelerated"):
        return "strix_cuda_cpu_cues"
    if npu.get("ready"):
        return "cpu_bvh_strix_npu"
    return "cpu_parity"


def _labels(ray: dict[str, Any], npu: dict[str, Any]) -> dict[str, str]:
    ray_label = "Strix CUDA/RTX" if ray.get("accelerated") else "CPU BVH Parity"
    npu_label = "Strix NPU Ready" if npu.get("ready") else "NPU Pending"
    if ray.get("accelerated") and npu.get("ready"):
        summary = "Strix CUDA/RTX + NPU"
    elif ray.get("accelerated"):
        summary = "Strix CUDA/RTX + CPU Cues"
    elif npu.get("ready"):
        summary = "CPU BVH + Strix NPU"
    else:
        summary = "CPU BVH + NPU Pending"
    return {
        "backend_label": ray_label,
        "npu_label": npu_label,
        "summary_label": summary,
    }


def collect_status(
    *,
    model_dir: Path | None = None,
    device: str | None = "NPU",
    host_label: str = "Strix",
    source_label: str | None = None,
) -> dict[str, Any]:
    """Collect local runtime status for display in the browser demo."""

    ray = _to_dict(inspect_ray_runtime())
    npu = _to_dict(IntelNPUSigLIP2Adapter(model_dir=model_dir, device=device).inspect_runtime())
    labels = _labels(ray, npu)
    compute_mode = _compute_mode(ray, npu)
    now = datetime.now(tz=UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    host = source_label or socket.gethostname() or "local"

    return {
        "generated_at": now,
        "host": host_label,
        "source": host,
        "ray": ray,
        "npu": npu,
        "ui": {
            **labels,
            "compute_mode": compute_mode,
            "stale_after_seconds": 300,
            "route_guard_use_case": "Automatic corridor geometry and local cue classification",
        },
        "pipeline": {
            "generated_by": "scripts/write_strix_compute_status.py",
            "model_dir": str(model_dir or DEFAULT_MODEL_DIR),
            "device": device or "auto",
        },
    }


def render_js(status: dict[str, Any]) -> str:
    payload = json.dumps(status, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/write_strix_compute_status.py.\n"
        "// Regenerate on Strix before a hardware demo.\n"
        f"window.{GLOBAL_NAME} = {payload};\n"
    )


def write_status(output: Path, status: dict[str, Any]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_js(status), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--model-dir", type=Path, default=DEFAULT_MODEL_DIR)
    parser.add_argument("--device", default="NPU")
    parser.add_argument("--host-label", default="Strix")
    parser.add_argument(
        "--source-label",
        default=None,
        help="Optional provenance label for the generated artifact.",
    )
    args = parser.parse_args(argv)

    status = collect_status(
        model_dir=args.model_dir,
        device=args.device,
        host_label=args.host_label,
        source_label=args.source_label,
    )
    write_status(args.output, status)
    print(json.dumps(status, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
