// Generated by scripts/write_classifier_cue.py.
// Regenerate after changing the packaged H100 classifier or demo frame.
window.TAC_FUSE_CLASSIFIER_CUE = {
  "classification": {
    "all_candidates": [
      {
        "confidence": 0.7140949964523315,
        "label": "low_power_return_corridor"
      },
      {
        "confidence": 0.17314571142196655,
        "label": "clear_corridor"
      },
      {
        "confidence": 0.04295086860656738,
        "label": "reduced_visibility_field_conditions"
      },
      {
        "confidence": 0.02861480414867401,
        "label": "drone_near_restricted_area"
      },
      {
        "confidence": 0.025930115953087807,
        "label": "low_altitude_clutter"
      },
      {
        "confidence": 0.01526354718953371,
        "label": "dense_multi_asset_formation"
      }
    ],
    "class_label": "low_power_return_corridor",
    "confidence": 0.7140949964523315,
    "device": "cpu",
    "frame_path": "reports/classifier_cue_route_guard.jpg",
    "inference_latency_ms": 2403.5928749945015,
    "model_id": "google/siglip2-base-patch16-224",
    "source_id": "siglip2_expanded_vehicle_hpo",
    "timestamp": "2026-05-03T20:06:50.994108+00:00",
    "track_id": "scene-vehicle-17"
  },
  "frame": {
    "path": "reports/classifier_cue_route_guard.jpg",
    "source": "synthetic_route_guard_vehicle_frame"
  },
  "generated_at": "2026-05-03T20:06:50Z",
  "package": {
    "artifact_type": "pytorch_siglip2_image_classifier",
    "base_model": "google/siglip2-base-patch16-224",
    "checksum_ok": null,
    "checksum_verified": false,
    "metrics": {
      "eval_accuracy": 0.6979166666666666,
      "eval_loss": 0.676681625812004,
      "eval_samples": 288,
      "score": 0.6302485040854662
    },
    "missing_paths": [],
    "model_dir": "models/siglip2-expanded-vehicle-hpo-best",
    "package_id": "siglip2-expanded-vehicle-hpo-best",
    "package_present": true,
    "ready_for_demo": true,
    "reason": "ready",
    "selection": {
      "completed_trials": 18,
      "framework": "Ax + BoTorch",
      "objective": "eval_accuracy - 0.10 * eval_loss",
      "trial_index": 14
    },
    "size_mismatches": []
  },
  "pipeline": {
    "device": "CPU",
    "generated_by": "scripts/write_classifier_cue.py",
    "manifest": "default",
    "model_dir": "models/siglip2-expanded-vehicle-hpo-best",
    "output": "web/classifier_cue.js",
    "track_id": "scene-vehicle-17"
  },
  "ready": true,
  "runtime": {
    "device": "cpu",
    "model_dir": "models/siglip2-expanded-vehicle-hpo-best",
    "model_id": "google/siglip2-base-patch16-224",
    "model_present": true,
    "package_id": "siglip2-expanded-vehicle-hpo-best",
    "ready": true,
    "reason": "ready",
    "runtime_dependencies": {
      "PIL": true,
      "google.protobuf": true,
      "sentencepiece": true,
      "torch": true,
      "torchvision": true,
      "transformers": true
    },
    "source_id": "siglip2_expanded_vehicle_hpo"
  },
  "top_candidates": [
    {
      "confidence": 0.7140949964523315,
      "label": "low_power_return_corridor"
    },
    {
      "confidence": 0.17314571142196655,
      "label": "clear_corridor"
    },
    {
      "confidence": 0.04295086860656738,
      "label": "reduced_visibility_field_conditions"
    },
    {
      "confidence": 0.02861480414867401,
      "label": "drone_near_restricted_area"
    },
    {
      "confidence": 0.025930115953087807,
      "label": "low_altitude_clutter"
    },
    {
      "confidence": 0.01526354718953371,
      "label": "dense_multi_asset_formation"
    }
  ],
  "ui": {
    "confidence_pct": 71,
    "cue_label": "low_power_return_corridor",
    "status_label": "Generated Model Cue"
  }
};
