// Generated by scripts/write_edge_compute_status.py.
// Regenerate on Strix before a hardware demo.
window.TAC_FUSE_EDGE_COMPUTE = {
  "classifier_package": {
    "artifact_type": "pytorch_siglip2_image_classifier",
    "base_model": "google/siglip2-base-patch16-224",
    "checksum_failures": [],
    "checksum_ok": null,
    "checksum_verified": false,
    "files": [
      {
        "bytes": 995,
        "exists": true,
        "expected_bytes": 995,
        "expected_sha256": "bc873a7ab2677f63bb7f93856ed9577dc0103b0ac97efddebbc2c2423837b56f",
        "path": "backbone/config.json",
        "size_ok": true
      },
      {
        "bytes": 1500800904,
        "exists": true,
        "expected_bytes": 1500800904,
        "expected_sha256": "d1f1e3f14c203cd8783595208445b63afea46098aa511220b40ec7f027eb162d",
        "path": "backbone/model.safetensors",
        "size_ok": true
      },
      {
        "bytes": 20616,
        "exists": true,
        "expected_bytes": 20616,
        "expected_sha256": "e7eb1cd6987e5b3e29adb0c33f1111ab6432401ecd3e5c6a0275ff6de498e414",
        "path": "classifier_head.pt",
        "size_ok": true
      },
      {
        "bytes": 591,
        "exists": true,
        "expected_bytes": 591,
        "expected_sha256": "ecd6ae513fe103f0eb62e8ab5bfa8d0fe45c1074fa398b089c93a7e70c15cfd6",
        "path": "processor/chat_template.jinja",
        "size_ok": true
      },
      {
        "bytes": 463,
        "exists": true,
        "expected_bytes": 463,
        "expected_sha256": "e4f8960049b5e0276caaf3d307ee03f1584f0ea5bfab702d60c03a4cc90d12b5",
        "path": "processor/processor_config.json",
        "size_ok": true
      },
      {
        "bytes": 34363038,
        "exists": true,
        "expected_bytes": 34363038,
        "expected_sha256": "caefd63119539a63be2d55ef3e05023fbb793948c4bda5bc0c366b42a382f903",
        "path": "processor/tokenizer.json",
        "size_ok": true
      },
      {
        "bytes": 655,
        "exists": true,
        "expected_bytes": 655,
        "expected_sha256": "f2c862b59d884624691cc4509acf15bd8d1503dee1b42314ddb521eab9609fd1",
        "path": "processor/tokenizer_config.json",
        "size_ok": true
      },
      {
        "bytes": 1028,
        "exists": true,
        "expected_bytes": 1028,
        "expected_sha256": "18ae179c72f5f4c847a8584ca1f80428e5ed7970e3d65517386268af2bd4b0b4",
        "path": "training_summary.json",
        "size_ok": true
      }
    ],
    "metrics": {
      "eval_accuracy": 0.6979166666666666,
      "eval_loss": 0.676681625812004,
      "eval_samples": 288,
      "score": 0.6302485040854662
    },
    "missing_paths": [],
    "model_dir": "/home/kearm/AlphaHENG/contrib/TAC-FUSE/models/siglip2-expanded-vehicle-hpo-best",
    "package_id": "siglip2-expanded-vehicle-hpo-best",
    "package_present": true,
    "ready_for_demo": true,
    "reason": "ready",
    "selection": {
      "completed_trials": 18,
      "framework": "Ax + BoTorch",
      "objective": "eval_accuracy - 0.10 * eval_loss",
      "trial_index": 14
    },
    "size_mismatches": []
  },
  "generated_at": "2026-05-03T17:24:18Z",
  "host": "Demo",
  "npu": {
    "device": "NPU",
    "model_dir": "models/siglip2-field-npu",
    "model_id": "google/siglip2-base-patch16-224",
    "model_present": false,
    "npu_device_visible": false,
    "openvino_available": false,
    "ready": false,
    "reason": "missing OpenVINO IR at models/siglip2-field-npu"
  },
  "pipeline": {
    "classifier_package": "/home/kearm/AlphaHENG/contrib/TAC-FUSE/models/siglip2-expanded-vehicle-hpo-best",
    "device": "NPU",
    "generated_by": "scripts/write_edge_compute_status.py",
    "model_dir": "models/siglip2-field-npu"
  },
  "ray": {
    "accelerated": true,
    "available": true,
    "backend": "rtx",
    "reason": "CUDA driver bindings importable; RTX BVH path may be selected"
  },
  "source": "local_classifier_package",
  "ui": {
    "backend_label": "Accelerated Geometry",
    "classifier_label": "H100 Classifier Packaged",
    "compute_mode": "accelerated_geometry",
    "npu_label": "Edge NPU Unverified",
    "route_guard_use_case": "Automatic corridor geometry and local cue classification",
    "stale_after_seconds": 300,
    "summary_label": "Accelerated Geometry"
  }
};
